name: Pages

on:
  push:
    branches:
      - xmain  # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.G_TOKEN }}
        
      - name: Checkout submodule
        run: |
          git config --file=.gitmodules submodule.lib/next-theme.url https://${{ secrets.G_TOKEN }}:${{ secrets.G_TOKEN }}@github.com/next-theme/hexo-theme-next.git
          git submodule sync
          git submodule update --force --recursive --init --remote --depth 0
      
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.G_TOKEN }}
          publish_dir: ./public
