name: Hexo Deploy GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: theme-keep/hexo-deploy-github-pages-action@master
      env:
        PERSONAL_TOKEN: ${{ secrets.G_TOKEN }}

        # The repository the action should deploy to.
        PUBLISH_REPOSITORY: allasca/allasca.github.io

        # The branch the action should deploy to.
        BRANCH: gh-pages
